name: Hospital app CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_STATIC_WEB_APP_NAME: 'swahospitalexercise'
  REACT_APP_API_BASE_URL: 'https://hospitalvisitsexerciseapi.azurewebsites.net'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2

      # Install dependencies and run tests
      - name: Install and Test
        run: |
          npm install
          npm test
        env:
          REACT_APP_API_BASE_URL: ${{ env.AZURE_RESOURCE_GROUP }}



      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build and Deploy to Azure Static Web App
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          api_location: ''
          output_location: 'build'
