name: React CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AZURE_STATIC_WEB_APP_NAME: ${{ env.AZURE_STATIC_WEB_APP_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install dependencies and run tests
      - name: Install and Test
        run: |
          npm install
          npm test

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy infrastructure using Bicep if not exists
      - name: Deploy Infrastructure
        run: |
          az deployment group create \
            --name reactDeployment \
            --resource-group myResourceGroup \
            --template-file ./devops/swa.bicep \
            --parameters staticWebAppName=$AZURE_STATIC_WEB_APP_NAME location=westeurope

      # Build and Deploy to Azure Static Web App
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          api_location: ''
          output_location: 'build'
